* Определения
** Полукольцо
   Штука, сожержащая пустое множество, все пересечения ее элементов, а так же
   всякая разница элементов составлена из какого-то дизъюнктного набора.

   Полукольцо подмножеств - это P ⊂ 2ˣ, такое, что
   1) ∅ ∈ P
   2) ∀ A, B ∈ P : A ∩ B ∈ P
   3) ∀ A ⊂ B ∈ P : ∃ D₁..Dᵣ - дизъюнкт. набор: B \ A = ⊔ Dᵢ

** Алгебра
   Уже лежит все множество X и всякая разница 2 множеств тоже уже лежит

   ℵ ⊂ 2ˣ - алгебра, если:
   1) ∀ A, B ∈ ℵ : A ﹨ B ∈ ℵ
   2) X ∈ ℵ
** Сигма-алгебра
   Любое счетное объединение элементов лежит в сигма-алгебре

   ℵ - σ-алгебра, если:
   1) ℵ - алгебра
   2) ∀ A₁, A₂... ∈ ℵ - счетный набор мн-в, ∪Aᵢ ∈ ℵ
** Объем
   Положительная конечно-аддитивная функция на полукольце

   Пусть P - полукольцо
   μ : P → ℝ⁺ - объем, если:
   1) μ конечно аддитивен (∀ A₁..Aᵣ ∈ P - кон. дизъюнкт. набор,
      ⊔ Aᵢ = A : μ(A) = ∑ μ(Aᵢ))
   2) μ(∅) = 0
** Ячейка
** Классический объем в ℝ^m
** Мера
   Мера - это счетно-аддитивный объем
** Формулировка теоремы о непрерывности сверху
** Формулировка теоремы о лебеговском продолжении меры
   μ₀ - σ-конечный объем на P₀. Тогда:
   ∃ ℵ ⊃ P₀, ℵ - σ-алгебра, μ - мера на ℵ, такая, что:
     1) μ - продолжение μ₀ с P₀ на ℵ
     2) μ - полная мера
     3) μ - минимальное продолжение, т.е.
        μ' - мера на σ-алгебре ℵ' - продолжение μ₀; μ' - полная ⇒ ℵ ⊂ ℵ' и μ'|ₐ = μ
     4) P₁ - полукольцо, P₀ ⊂ P₁ ⊂ ℵ, μ₁ - продолж. μ₀ на P₁ ⇒ сужение μ на P₁ = μ₁
     5) ∀ A ∈ ℵ : μ(A) = inf {∑ μ(Pᵢ), A ⊂ ∪Pᵢ, Pᵢ ∈ P₀}
** Полная мера
   Мера полна, если при ней любое подмножество множества нулевой меры
   также имеет нулевую меру.

   μ : P -> ℝ⁺ - мера,
   μ - полная мера, если ∀ A ∈ P, μ(A) = 0 : ∀ B ⊂ A , B ∈ P : μ(B) = 0
** Сигма-конечный объем
   Сигма-конечный объем - такой объем, при котором все множество
   можно представить в виде счетного объединения множеств конечного объема.

   P ⊂ 2ˣ - полукольцо
   μ : P → ℝ⁺ - объем
   μ - σ-конечен, если ∃ A₁, A₂.. - счетный набор мн-в. : ∀ i : μ(Aᵢ) < ∞, ∪ Aᵢ = X
** Сигма-конечная мера
   То же самое, что σ-конечный объем, только мера
** Мера Лебега, измеримое по Лебегу множество
   Мера Лебега - результат Лебеговского продолжения классического объема на сигма-алгебру
** Борелевская сигма-алгебра в ℝᵐ
   Борелевская σ-алгебра - наименьшая σ-алгебра, вкл. в себя все открытые подмножества ℝᵐ
   иначе:

   ℵ₀ ⊂ 2ʳᵐ - σ-алгебра
   ℵ₀ - борелевская σ-алгебра, если:
   Q = { ∀ A : A ⊂ X, A - открыто } ⊂ ℵ₀;
   ∀ ℵ ⊂ 2ʳᵐ, ℵ - σ-алгебра, Q ⊂ ℵ : ℵ₀ ⊆ ℵ
** Формулировка теоремы о мерах, инвариантных относительно сдвигов
   Меры, инвариантные относительно сдвига, отличаются от меры Лебега на константу

   Пусть Pᵐ ⊂ ℵ ⊂ Mᵐ, μ - мера на ℵ, μ - инв. отн. сдвига, т. е.:
   ∀ T - сдвиг, ∀ A ∈ ℵ : T(A) ∈ ℵ, μ(A) = μ(T(A))
   Тогда ∃ C > 0 : ∀ A ∈ ℵ : μ(A) = C · λ(A)
** Ступенчатая функция
   Ступенчатая функция - это у которой график ступеньками))

   f: X → ℝ - ступенчатая функция, если ∃ ⊔Xᵢ = X: f|ₓᵢ = Cᵢ (константа)
** Разбиение, допустимое для ступенчатой функции
   Любое разбиение X, подходящее под предыдущее определение (дизъюнктное, покрывающее все X)
** Измеримая функция
   Функция такая, что все Лебеговы множества этой функции измеримы данной мерой.

   Лебегово множество E(f < a) - это множество, на котором выполняется условие внутри скобок.

   (X, ℵ. μ) - пр-во с мерой
   f: X → ℝ - измерима, если ∀ a ∈ ℝ: X(f < a), X(f ≤ a), X(f > a), X(f ≥ a) ∈ ℵ

** Свойство, выполняющееся почти везде
   Свойство, выполняющееся везде. кроме множества точек нулевой меры.

   P: E → Bool - свойство, E - мн-во. P(x) почти везде на E,
   если P(x) ∀ x ∈ E \ X, μ(X) = 0

** Сходимость почти везде
   Ровно по предыдущему опр-ю.

   fₙ → f почти везде на E, если X ⊂ E, μX = 0,
   ∀ x ∈ E \ X : fₙ(x) → f(x)

** Сходимость по мере
   fₙ сходится к f по мере, если всякое Лебегово множество их разности стремится к нулю.

   fₙ, f - измеримы на мн-ве Е. ∀ δ > 0: E(|fₙ - f| ≥ δ) - измеримо
   fₙ ⇒ f по мере μ на мн-ве Е, если ∀ δ > 0: μE(|fₙ - f| ≥ δ) → 0.
** Теорема Егорова о сходимости почти везде и почти равномерной сходимости
   Если fₙ, f измеримы почти везде **конечной** мерой и fₙ → f почти везде, то
   эта сходимость "почти равномерна", что значит:

   (X, ℵ, μ), μX < +∞, fₙ → f почти везде на X
   ∀ ε > 0 ∃ E ⊂ X, E - измеримо, μE < ε : fₙ ⇉ f на X \ E
** Интеграл ступенчатой функции
   Интеграл ступенчатой функции - сумма площадей ступенек ))

   (X, ℵ, μ). f : X → ℝ - ступ. функция, f = ∑ aᵢₑᵢ
   ₓ∫f dμ = ∑ aᵢ · μ(Eᵢ ∩ X)
** Интеграл неотрицательной измеримой функции
   Это супремум интегралов всех ступенчатых функций, меньших данной.

   (X, ℵ, μ). f - изм. на X
   ₓ∫ fdμ = sup { ₓ∫ gdμ | g - ступ. ф-ция, 0 ≤ g ≤ f }
** Суммируемая функция
   Суммируемая функция - измеримая функция, у которой интегралы для обоих срезок
   определены и конечны.

** Интеграл суммируемой функции
   Разница интегралов срезок

   (X, ℵ, μ). f - суммируема на X.
   ₓ∫fdμ = ₓ∫f₊dμ - ₓ∫f₋dμ

** Лебега о мажорированной сходимости для сходимости по мере
   KW: РАЗНИЦЫ МАЛЕНЬКИЕ, МНОЖЕСТВА МАЛЕНЬКИЕ
   Если посл. функций сходится по мере и имеет суммируемую мажоранту, то интегралы разностей сходятся.

   (X, A, μ)
   f, fₙ : X → ℝ, fₙ ⇒ f по мере μ,
   ∃ g : g - суммируемая и |fₙ| ≤ g для почти всех x, тогда
   fₙ, f суммируемые и ∫|f - fₙ| → 0
** Теорема о произведении мер
   KW: ХАРАКТЕРИСТИЧЕСКИЕ ФУНКЦИИ
   Произведение мер есть мера на декартовом произведении пространств

   Пусть (X, ℵ, μ), (Y, ℶ, ν), μ, ν - меры, σ-конечные
   Тогда m(A × B) = μ(A)·ν(B) - σ-конечная мера в X × Y.
** Теорема Тонелли
   KW: ПРИНЦИП КАВАЛЬЕРИ, ПО ИНДУКЦИИ
   Это о том, что интеграл по площади можно разбить на 2 интеграла - по ширине и высоте,
   причем в разном порядке.

   (X, ℵ, μ), (Y, ℶ, ν), μ, ν - σ-конечные, полные, m=μ×ν
   f: X × Y → ℝ, f ≥ 0, измеримая

   Обозначение: fₓ = y ↦ f(x, y)

   Тогда выполнено:
   1. fₓ - ν-измерима при почти всех x
   2. fʸ - μ-измерима при почти всех y
   3. x → φ(x) := ∫fₓdν - μ-измеримaя функция
   4. X×Y_∫ fdm = Y_∫ φ(x) dμ(x) = ∫ (∫f(x, y)dν(y)) dμ(x) = ∫ (∫f(x, y)dμ(x)) dν(y)
** Теорема Фубини
   KW: СРЕЗКИ ФУНКЦИЙ, ТЕОРЕМА ТОНЕЛЛИ
   Ну, вроде то же самое, что Тонелли, только для произвольной суммируемой функции

   (X, A, μ), (Y, B, ν), μ,ν - σ-конечные, полные, m=μ×ν
   f: X × Y → ℝ~ - m-суммируемая

   Тогда:
   1. fₓ - суммируема п. в. на X, fʸ - сумм. п. в. на Y
   2.
      1. x ↦ φ(x) := ∫fₓdν  - сумм.* на X
      2. y ↦ ψ(y) := ∫fʸdμ  - сумм.* на Y
   3. ∫ fdm = ∫ φ(x)dμ = ∫ ψ(y)dν
** Образ меры при отображении
   Образ меры при отображении - новая мера, которая получается применением ко множеству
   обратного отображения и старой меры.

   (X, ℵ, μ), (Y, ℶ, _)
   Пусть есть отображение Ф:X → Y, причем
   Φ⁻¹(ℶ) = {Φ⁻¹(B), B ∈ ℶ}, Φ⁻¹(ℶ) ⊆ ℵ
   тогда ∀B ∈ ℶ ν(B) = μ(Φ⁻¹(B)) -- это образ меры при отображении
** Взвешенный образ меры
   Взвешенный образ меры - это мера, которая представляет собой интеграл весовой
   функции по прообразу аргумента по старой мере.

   (X, ℵ, μ), (Y, ℶ, _)
   w - вес, w ≥ 0, измерима,
   Φ: X → Y, Φ⁻¹(ℶ) ∈ ℵ
   ν(B) = ∫_Φ⁻¹(B) wdμ - взвешенный образ меры μ
** Плотность одной меры по отношению к другой
   Если есть две меры на одной и той же алгебре, и одна из них - взвешенный образ
   этой меры с отображением id, тогда весовая функция второй меры - это и есть
   плотность этой меры относительно другой.

   X = Y, ℵ = ℶ, Φ = id,
   w - вес, положительная измеримая ф-я,
   f - измеримая на X
   ν(B) = ∫_B wdμ, ∫fdν=∫f(x)w(x)dμ
   тогда вес w - это плотность ν относительно μ.
** Измеримое множество на простой двумерной поверхности в ℝ³
   Кусок простой двумерной поверхности измерим, если измерим его гладкий прообраз в ℝ²

   M - простая гл. 2-мерная пов. в ℝ³
   φ : Ω ⊂ ℝ² → ℝ³ - гладкая
   A ⊂ M - измеримо (по Лебегу), если φ⁻¹(A) - измеримо
** Мера Лебега на проcтой двумерной поверхности в ℝ³
   Получаем меру как взвешенный образ обычной меры (с якобианом)

   σ(A) = Ф⁻¹(A)_∫ |det Ф'|dudv
** Поверхностный интеграл первого рода
   A_∫fdS = Ф⁻¹(A)_∫f ∘ Ф sqrt(EG - F²)dudv
   где
   E = xᵤ'² + yᵤ'² + zᵤ'²
   G = xᵥ'² + yᵥ'² + zᵥ'²
   F = xᵤ'xᵥ' + yᵤ'yᵥ' + zᵤ'zᵥ'
** Кусочно-гладкая поверхность в ℝ³
   Поверхность кусочно-гладкая, если она является объединением
   конечного числа простых гладких поверхностей
   конечного числа простых гладких дуг
   конечного числа отдельных точек
** Сторона поверхности
   Сторона поверхности - нормальный вектор к ней.
** Задание стороны поверхности при помощи касательных реперов
   Нормальный вектор выражается через 2 касательных как векторное произведение

   nₒ(x) = (v₁(x) × v₂(x))/|v₁(x) × v₂(x)|
** Интеграл второго рода
   Интеграл второго рода по поверхности - интеграл скалярного произведения векторного поля на сторону
   m∫<F, n₀>dσ
** Ориентация контура, согласованная со стороной поверхности
   Такая ориентация контура, что соблюдается правило буравчика/правой руки для выбранной нормали
   к поверхности
** Ротор, дивергенция векторного поля
   V = (P, Q, R)
   rot V = (R_y' - Q_z', P_z' - Rₓ', Qₓ' - P_y')
   div V = Pₓ' + Q_y' + R_z'
** Соленоидальное векторное поле
   Поле соленоидальное, если для него существует векторный потенциал,
   то есть такое B, что V = rot B
** Бескоординатное определение ротора
   Ротор - предел интеграла векторного поля по контуру, который стягивается в точку.
** Бескоординатное определение дивергенции
   Дивергенция - предел интеграла векторного поля по поверхности, которая стягивается в точку.
** Интегральные неравенства Гельдера и Минковского
   p, q > 1, 1/p + 1/q = 1; f, g - измеримы* и п.в. конечны.

   ∫|fg| ≤ (∫|f|ᵖ)^(1/p) · (∫|g|^q)^(1/q) - неравенство Гельдера

   p ≥ 1
   (∫|f + g|ᵖ)^(1/p) ≤ (∫|f|ᵖ)^(1/p) + (∫|g|ᵖ)^(1/p) - неравенство Минковского

   Оно задает норму на функциях: |f + g| ≤ |f| + |g|
** Интеграл комплекснозначной функции
   f : X → C⁺ (комплексные числа + ∞)
   1) f - измерима, если Re f и Im f - измеримы
   2) ∫f = ∫Re f + i∫Im f, f - суммируема, если Re и Im суммируемы
** Пространство Lᵖ(E, μ)
   Линейное пространство классов измеримых функций с нормой Минковского с параметром p.

   {f: X → C⁺, f - изм, (∫|f|ᵖ)^(1/p) < +∞} - нормированное Л.П. в силу нер-ва Минковского
   там есть 0 - любая п.в. нулевая функция.
   Возьмем это пространство и факторизуем его по отношению равенства почти везде.
   Получится пространство Lᵖ
** Пространство L∞(E, μ)
   Линейное пространство классов существенно ограниченных измеримых функций

   L∞ = ({f - изм, esssup f < +∞})⁼, где (·)⁼ - факторизация по отн. равенства почти везде.
** Существенный супремум
   Существенный супремум - супремум почти везде.

   esssup f = {M ∈ ℝ⁺, f(x) ≤ M почти везде}
** Фундаментальная последовательность, полное пространство
   Фундаментальная последовательность - сходящаяся в себе

   Пусть X - норм. пространство, xₙ ∈ X - фундаментальная последовательность, если
   ∀ ε > 0 ∃ N ∀ n, m > N : |xₙ - xₘ| < ε

   Полное пространство - это где любая фунд. последовательность сходится

   X - полно, если ∀ xₙ - фунд. посл-ть : ∃ lim xₙ ∈ X
** Плотное множество
   Множество всюду плотно, если оно пересекается с любым открытым множеством.

   X - метр. пр-во. A ⊂ X - (всюду) плотно на X, если ∀ O ⊂ X - открытое мн-во,
   O ∩ A ≠ ∅
** Финитная функция
   f - финитна, если f = 0 за пределами некоторого шара.
** Несобственный интеграл Лебега в {\mathbb R}
** Условие Lₗₒₖ
   В любой окрестности y₀ функция ограничена сверху какой-то суммируемой функцией, не зависящей от y

   Функия f удовлетворяет условию Lₗₒₖ(y₀) если
   ∀ U_{y₀} : ∃g(x) - суммируемая : ∀y ∈ U_{y₀}, ∀x, |f(y, x)| ≤ g(x) и g(x) суммируемая
** Тригонометрический ряд
   Тригонометрический ряд - ряд вида
   a₀/2 + ∑(aₖcoskx + bₖsinkx)
   (или в комплексном случае: ∑Cₖeⁱᵏˣ)
** Коэффициенты Фурье функции
   Коэффициенты Фурье функции - это коэффициенты рядом с синусом и косинусом в разложении
   функции в тригонометрический ряд.

   f ∈ L¹[π, π], тогда aₖ(f), bₖ(f), Cₖ(f) - коэф-ты Фурье f,
   а ряд aₒ/2 + ∑aₖcoskx + ∑bₖsinkx (∑Cₖe⁻ⁱᵏˣ) - ряд Фурье этой функции
** Ядро Дирихле, ядро Фейера
   1) Ядро Дирихле - функция Dₙ(t) = (1/π)·(1/2 + ∑ₖⁿ cos(kt)) = (sin((n+1/2)t))/2πsin(t/2)
   2) Ядро Фейера - функция Фₙ(t) = (1/(n+1)) · ∑ₖⁿDₖ(t) = (1/(2π(n + 1))) · (sin²((n+1)/2)t)/(sin²(t/2))
** Свертка
   Свертка двух функций - это интеграл, в котором одна функция как бы "наматывается"
   на другую вокруг данной точки
   f, K ∈ L¹[-π, π].
   Свертка - это ф-ция (f ⋆ K)(x) = ₋ₚᵢ∫ᵖⁱ f(t)K(x - t)dt = ₋ₚᵢ∫ᵖⁱ f(x - t)K(t)dt
** Аппроксимативная единица
   Семейство функций, интеграл которых равен единице, интегралы норм ограничены,
   и при приближении параметра к некой точке интегралы норм сходятся к нулю

   Пусть D ⊂ ℝ, xₒ ∈ ℝ⁺, xₒ - предельная точка D.
   ∀ h ∈ D определена ф-ция Kₕ(x) со след. свойствами:
   1) Kₕ ∈ L¹[-π, π], ₋ₚᵢ∫ᵖⁱ Kₕ(t)dt = 1
   2) ∃ M ∀ h ∈ D : ∫|Kₕ| ≤ M
   3) ∀ δ > 0 : ₑ∫|Kₕ| → 0 при h → x₀

   Тогда семейство Kₕ называется аппроксимативной единицей
** Усиленная аппроксимативная единица
   Усиленная аппроксимативная единица - это которая еще и существенно ограничена,
   и ее существенный супремум стремится к 0.

   Если Kₕ ∈ L∞[-π, π], esssup|Kₙ| → 0 при h → x₀. Тогда
   Kₕ - усиленная аппроксимативная единица
** Метод суммирования средними арифметическими
   Вместо устремления частичных сумм к бесконечности устремляем средние
   арифметические частичных сумм

   ∑ аₙ (ср. ариф) = lim{n → ∞} (S₀ + S₁ + .. + Sₙ)/(n + 1)