** LEARNED Свойства объема: усиленная монотонность, конечная полуаддитивность, субтрактивность
   Усиленная монотонность: если некоторый дизъюнктный набор множеств содержится
   в одном большом множестве, то объем большого множества не меньше суммарного объема
   всех маленьких множеств из набора

   μ: P → ℝ⁺, A₁..Aᵣ ∈ P - дизъюнкт. набор, ⊔Aᵢ ⊂ A ∈ P, тогда ∑ μ(Aᵢ) ≤ μ(A)

   Конечная полуаддитивность: если некое большое множество покрывается набором
   маленьких, то объем большого не больше суммарного объема маленьких

   A₁..Aᵣ, A ∈ P, A ⊂ ∪Aᵢ ⇒ μ(A) ≤ ∑μ(Aᵢ)

   Субтрактивность: объем разности двух множеств есть разность их объемов

   A ⊂ B ∈ P, μ(B) < ∞ ⇒ μ(B ﹨ A) = μ(B) - μ(A)

   ▷
   1) Возьмем дизъюнктный набор разниц между A и Аₖ. Мера А – сумма мер этих двух наборов.
   2) Волевым усилием обрежем Aᵢ так, чтобы получился дизъюнктный набор, равный A. Сумма мер обрезков ≥ 0
   3) Разница м\у В и А - это некоторый дизъюнктный набор, пошафлим этот факт - получим нужное выражение для его меры.
   ∎
** LEARNED Теорема об эквивалентности счетной аддитивности и счетной полуаддитивности
   μ : P → ℝ⁺ - объем

   Счет. аддитивность: A₁, A₂... ∈ P - счетный дизъюнкт. набор, A ∈ P, A = ⊔Aᵢ ⇒
   ⇒ μ(A) = ∑ μ(Aᵢ) (сумма ряда)

   Счет. полуаддитивность: A₁, A₂... ∈ P - счетный набор, A ∈ P, A ⊂ ∪Aᵢ ⇒
   ⇒ μ(A) ≤ ∑ μ(Aᵢ) (сумма ряда)

   Эти два свойства эквивалентны.

   ▷
   1 ⇒ 2: то же, что и в свойствах объема, только счетное.
   2 ⇒ 1: Берем дизъюнктный набор, содержащий А.
   ≤ уже доказано - полуаддитивность дана
   ≥ работает по усиленной монотонности
   ∎
** LEARNED Теорема о непрерывности снизу
   Если объем на алгебре является мерой, то он непрерывен снизу, и наоборот

   μ : ℵ → ℝ⁺. Эквивалентно:
   1) μ - мера
   2) μ - непрерывен снизу, т. е.
      A₁ ⊂ A₂ ⊂ ... ∈ ℵ, A ∈ ℵ
      A = ∪ Aᵢ ⇒ μ(A) = lim μ(Aᵢ), i → ∞

   ▷
   1 ⇒ 2: Берем "колечки" от Aᵢ - дизъюнктный набор равный A Мера А - предел
   их частичных сумм, а значит - предел Aᵢ
   2 ⇒ 1: Делаем то же самое, только наоборот: в этом случае пользуемся конечной аддитивностью.
   ∎
** LEARNED Счетная аддитивность классического объема
   Классический объем счетно аддитивен (wow!), то есть является мерою (причем σ-конечной!).

   μ: Pᵐ → ℝ⁺, Pᵐ - кольцо ячеек в ℝᵐ (параллелепипеды [a, b))
   μ[a, b) = ∏(bᵢ - aᵢ) - классический объем.
   Пусть A₁, A₂... ∈ Pᵐ - дизъюнкт. счетный набор параллелепипедов, A = ⊔Aᵢ ∈ Pᵐ
   ⇒ μ(A) = ∑ μ(Aᵢ)

   ▷
   σ-конечность очевидна - просто будем брать большие-пребольшие ячейки
   Докажем счетную полуаддитивность: очень нагло наберем различных закрытых/открытых
   параллелепипедов, скажем, что их меры отличаются на какие-то там эпсилоны,
   Так же внаглую напишем счетное неравенство для левых параллелепипедов, потом добавим эпсилоны
   и перейдем к ячейкам
   ∎
** Лемма о структуре открытых множеств и множеств меры 0
** LEARNED Пример неизмеримого по Лебегу множества
   Возьмем отношение эквивалентности на [0, 1]: x ~ y, если x - y ∈ Q.
   Выберем представителя из каждого класса эквивалентности - множество представителей неизмеримо
** LEARNED Регулярность меры Лебега
   Всякое измеримое множество можно окружить 2-мя множествами
   изнутри и снаружи так, что получившаяся проскойка будет сколь угодно маленькой.

   ∀ A ∈ Mᵐ: sup {λ(X) | X ∈ Mᵐ - замкнутое, X ⊂ A} = λ(A) = inf {λ(G) | G ∈  Mᵐ - открытое, A ⊂ G}

   ∀ A ∈ Mᵐ:
   1) ∀ ε > 0 ∃ G ∈ Mᵐ - открытое, A ⊂ G : λ(G ∖ A) < ε
   2) ∀ ε > 0 ∃ X ∈ Mᵐ - замкнутое, X ⊂ A : λ(A ∖ X) < ε

   ▷ ХЗ ∎
** LEARNED Лемма о сохранении измеримости при непрерывном отображении
   Воздействуя непрерывным отображением, сохраняющим ноль, на множество,
   мы не повлияем на его измеримость.

   Пусть T ∈ C(ℝᵐ → ℝᵐ), ∀ A ∈ Mᵐ , λ(A) = 0 : λ(T(A)) = 0
   Тогда ∀ A ∈ Mᵐ : T(A) ∈ Mᵐ

   ▷
   Если А ограничено, то оно делится на дизъюнктный набор компактов и что-то меры 0.
   Непрерывное отображение сохраняет компакт => в результате множество тоже будет состоять
   из компактов и нулевого - будет измеримо.
   Если неограничено - вступает в силу сигма-конечность.
   ∎
** LEARNED Теорема о сохранении измеримости при гладком отображении
   Гладкое отображение сохраняет измеримость множества

   Пусть F ∈ C¹(O ⊂ ℝᵐ → ℝᵐ)
   Тогда ∀ A ∈ Mᵐ, A ⊂ O : F(A) ∈ Mᵐ

   ▷
   Докажем сохранение нуля. Покроем нулевое множество кубами, и покажем,
   что благодаря теореме Лагранжа эти кубы не сильно растянутся, и смогут быть ограничены
   эпсилоном.
   ∎
** LEARNED Инвариантность меры Лебега относительно сдвигов
   Если мы подвинем множество, его мера не изменится.

   Пусть x₀ ∈ ℝᵐ, T : ℝᵐ → ℝᵐ , T(x) = x + x₀
   Тогда ∀ A ∈ Mᵐ : λ(A) = λ(T(A))

   ▷
   Разобьем все на ячейки - с ними сдвиг точно ниче не делает.
   Сдвиг непрерывен, и докажем сохранение нуля по 5 пункту Лебеговского продолжения.
   Тогда вся измеримость сохранится и результирующая мера будет той же.
   ∎
** LEARNED Инвариантность меры Лебега при ортогональном преобразовании
   При всяком ортогональном преобразовании (перенос, поворот) мера Лебега не меняется.

   Пусть T: ℝᵐ → ℝᵐ - ортогональное преобразование
   Тогда ∀ A ∈ Mᵐ: T(A) ∈ Mᵐ, λA = λT(A)

   ▷
   Делаем примерно то же самое, что и со сдвигом, только пользуемся
   шарами, а не ячейками, и в конце внаглую говорим, что мы знаем свойство
   инвариантных относительно сдвига мер.
   ∎
** LEARNED Лемма "о структуре компактного оператора"=
   Компактный линейный оператор можно задать 2 базисами и набором коэффициентиков
   через ебаную сумму со скалярными произведениями.

   Пусть V : ℝᵐ → ℝᵐ - невырожденный линейный оператор.
   Тогда ∃ hᵢ, gᵢ - базисы в ℝᵐ и sᵢ - набор коэффициентов, такие, что
   ∀ x ∈ ℝᵐ : V(x) = ∑ sᵢ<x, gᵢ>hᵢ,
   причем |det V| = s₁ · s₂ · ... · sm

   ▷
   Линааал))) Делаем вид, что знаем его
   Берем W = VᵗV, берем его собственные числа и базис из собственных векторов.
   С помощью линальной магии строим еще один набор векторов, доказываем что он базис,
   потом подставляем разложение икса по базису в выражение V(x), шафлим и вуаля!
   ∎
** LEARNED Теорема о преобразовании меры Лебега при линейном отображении
   Линейное отображение сохраняет измеримость и домножает меру на свой
   определитель.

   Пусть V : ℝᵐ → ℝᵐ - линейное отобр-е. Тогда:
   ∀ A ∈ Mᵐ : V(A) ∈ Mᵐ, λ(V(A)) = |det V| · λ(A) (считаем, что 0 · ∞ = 0)

   ▷
   Если оператор вырожден, то все множества что он выплевывает будут нулевыми.
   Если нет, то т. к. линейность => гладкость - измеримость сохраняется.
   Вспоминаем голословную инвариантность относительно сдвигов, считаем на кубике,
   получаем нужную константу.
   ∎
** LEARNED Теорема об измеримости пределов и супремумов
   Пределы (верхний/нижний) и супремумы/инфиумы последовательности измеримых функций измеримы.

   fₙ - посл-ть измеримых функций. Тогда:
   1) sup{fₙ}, inf{fₙ} - измеримы
   2) ulim fₙ, llim fₙ - измеримы
   3) если lim fₙ = f - существует, то f - измерима

   ▷
   из 2 сразу следует 3, доказать надо первые 2:
   1) Возьмем Лебегово множество для супремума по > a - это пересечение таких
      же множеств для всех fₙ - измеримо. Для инфиума так же.
   2) Возьмем функцию - супремум остатка последовательности, тогда верхний предел - это
      инфиум этой функции, а значит - измерим по п. 1
   ∎
** LEARNED Характеризация измеримых функций с помощью ступенчатых. Следствия.
   Всякую неотриц. измеримую функцию можно представить как предел возрастающей
   последовательности ступенчатых функций.

   Пусть f ≥ 0 - измерима на X, тогда ∃ gₙ - последовательность ступ. функций,
   такая, что ∀ x ∈ X:
   1) 0 ≤ gₙ ≤ f
   2) ∀ k: gₖ ≤ gₖ₊₁
   3) lim gₙ = f

   Следствие 1: это работает и для знакопеременных функций. только |gₙ| ≤ |f|
   Следствие 2: это работает для произведения измеримых функций.

   ▷
   Возьмем в общем ступенчатую функцию hₙ, которая прилегает снизу к f, и чем больше n,
   тем сильнее прилегает (кусочки разбиения сокращаются). Тогда для нее будут выполняться
   все условия кроме монотонности по n; исправим это, взяв gₙ = max {h₁ .. hₙ}

   Следствие 1: берем + и - срезки, применяем для них
   Следствие 2: берем произведение ступенчатых функций
   ∎
** LEARNED Измеримость монотонной функции
** LEARNED Теорема Лебега о сходимости почти везде и по мере
   Если последовательность функций сходится почти везде в пространстве **конечной** меры, то она сходится по мере.

   (X, ℵ, μ) - пространство конечной меры: μX < +∞
   fₙ → f почти везде на X. Тогда fₙ ⇒ f по мере

   ▷
   Достроим функции на множестве нулевой меры так, чтоб они сходились и на ней.
   1. Сначала докажем для fₙ ≥ 0, f = 0, fₙ - монотонно убывает по n.
   Для всякого эпсилона лебегово множество fₙ большего эпсилона включает в себя
   такое же следующее - это счетный набор вложенных множеств, и его пересечение = ∅.
   По непрерывности меры сверху их меры стремятся к нулю.
   2. Перейдем к произвольным функциям: возьмем функцию gₙ = sup |fₖ - f| ∀ k ≥ n
   Применим 1 пункт к ней и все ок.
   ∎
** LEARNED Теорема Рисса о сходимости по мере и почти везде
   Если fₙ сходится к f по мере, то *некоторая подпоследовательность* сходится к fₙ почти везде.

   (X, ℵ, μ), fₙ ⇒ f по μ. Тогда ∃ nₖ: fₙₖ → f почти везде.

   ▷
   Возьмем nₖ, которая с каждым шагом все сильнее (1/2ᵏ) уменьшает меру разницы.
   Возьмем хитрую последовательность вложенных множеств Eₖ, похожих на определение
   сходимости по мере. По непрерывности сверху и хитрому определению nₖ их пересечение будет
   иметь меру 0, а для всех иксов не из пересечения выясняется, что на них при больших
   k нет границы сближения с f.
   ∎
** LEARNED Простейшие свойства интеграла Лебега
   Интеграл Лебега монотонен, сохраняет 0 и 1, сохраняет нулевую меру,
   позволяет выносить константу, подчиняется "неравенству треугольника" с модулями,
   монотонен отн. константы и суммируемая функция должна быть конечной почти всюду.

   1) f ≤ g - сумм. ф-ции ⇒ ∫f ≤ ∫g      - монотонность
   2) ₓ∫1dμ = μX, ∫0dμ = 0               - сохранение 0 и 1
   3) ∀ E: μE = 0: ₑ∫f = 0               - сохранение мн-ва нулевой меры
   4) ∀ α ≥ 0: ∫αf = α∫f, ∫(-f) = -∫f    - вынесение константы за интеграл
   5) |∫f| ≤ ∫|f|                        - неравенство треугольника
   6) a ≤ f ≤ b: a · μX ≤ ₓ∫f ≤ b · μX   - монотонность отн. константы
   7) f - сумм ⇒ f - конечна п. в.       - требование о конечности почти везде

   ▷
   Все доказывается тривиально подъемом от ступенчатых функций или банальной ссылкой
   на прошлые свойства, кроме 6го - там нужно брать множества, на которых f > n, объединять
   их и смотреть че выходит.
   ∎
** LEARNED Счетная аддитивность интеграла (по множеству)
   Интеграл Лебега счетно аддитивен по множеству)))

   (X, ℵ, μ), ⊔ Aₖ = A ⊂ X, f - сумм. на A.
   Тогда ₐ∫fdμ = ∑ ₐₖ∫fdμ

   ▷
   Сначала доказываем ≤ - там просто переходим к ступенчатой функции,
   для которой счетная аддитивность верна (легко доказать) и в неравенстве переходим
   к супремуму
   Потом ≥ - начинаем с 2 множеств, берем 2 ступ. функции на них, сумма их интегралов меньше
   интеграла f - переходим к супремуму, потом по индукции доказываем справедливость для
   счетного набора.
   ∎
** LEARNED Теорема Леви о предельном переходе под знаком интеграла
   Под интегралом Лебега можно делать предельный переход, если последовательность функций
   положительна и монотонно возрастающая.

   f ≥ 0 - изм., ∀ x ∀ n: 0 ≤ fₙ(x) ≤ fₙ₊₁(x) ≤ f(x)
   fₙ → f п. в.
   Тогда lim ∫fₙdμ = ∫fdμ

   ▷
   ≤ - очевидно, по монотонности интеграла
   ≥ - какая-то ебаная магия, берем ступенчатую функцию для f, прихерачиваем к ней константу,
   разбиваем пространство на хитрые множества зависящие от n, получаем чудо-неравенство в котором
   можно сделать предельный переход и получить ровно то, что надо (только к супремуму надо перейти)
   ∎
** LEARNED Линейность интеграла
   Интеграл Лебега линеен))

   f, g ≥ 0: ∫(f + g) dμ = ∫f + ∫g

   ▷
   Берем последовательности ступ. функций, стремящихся к f и g, делаем сумму для
   их интегралов и делаем предельный переход
   ∎

** LEARNED Лебега о мажорированной сходимости для сходимости по мере
   KW: РАЗНИЦЫ МАЛЕНЬКИЕ, МНОЖЕСТВА МАЛЕНЬКИЕ
   Если посл. функций сходится по мере и имеет суммируемую мажоранту, то интегралы разностей сходятся.

   (X, A, μ)
   f, fₙ : X → ℝ, fₙ ⇒ f по мере μ,
   ∃ g : g - суммируемая и |fₙ| ≤ g для почти всех x, тогда
   fₙ, f суммируемые и ∫|f - fₙ| → 0

   ▵

   fₙ, а значит, f - суммируемы, так как ограничены по модулю суммируемой g.
   Рассмотрим 2 случая:
   1) μX < +∞
      Xₙ = X(|fₙ - f| > ε), по опр. сходимости по мере, μXₙ → 0
      Теперь разобьем ₓ∫|fₙ - f| = ₓₙ∫ + ₋ₓₙ∫, обе части норм оценятся сверху, ведь -Xₙ - конечна.
   2) μX = +∞
      Докажем, что есть такой конечный А, что интеграл мажоранты по X\A мал.
      Для этого возьмем A = носитель ступенчатой функции, прилегающей к g.
      Тогда X_∫ = A_∫ + (X\A)_∫ - оценивается, ведь А - конечно (по 1 пункту все ок),
      и (X\A)_∫ мало по построению.
   ▿
** LEARNED Лебега о мажорированной сходимости для сходимости почти везде
   KW: РАЗНОСТИ УБЫВАЮТ, С МАЖОРАНТОЙ - РАСТУТ, ЛЕВИ
   Если посл. функций сходится почти везде и имеет суммируемую мажоранту, то интегралы разностей сходятся.

   (X, ℵ, μ), fₙ, f: X → ℝ~, fₙ → f почти везде
   ∃g, суммируемая, ∀n : |fₙ| ≤ g для почти всех x
   Тогда:
   fₙ, f - суммируемые, ∫|fₙ - f|dμ → 0

   ▵
   fₙ, f суммируемы как и в прошлой теореме.
   Возьмем hₙ - супремумы разностей модулей, hₙ ≥ hₙ₊₁
   Они также оцениваются сверху мажорантой (2g).
   Посмотрим на предел lim ∫ (2g - hₙ), теорема Леви - и ок. ∫hₙ → 0, это то что надо
   ▿
** LEARNED Теорема Фату
   KW: ИНФИУМ, ЛЕВИ
   Если посл-ть сходится к f почти везде, и каждый член последовательности чем-то
   сверху ограничен, то f ограничена так же.

   (X, ℵ, μ)
   fₙ → f почти везде по X, и ∃ C : ∀ n : ∫fₙdμ < C, тогда
   ∫fdμ < C

   ▵
   Возьмем gₙ - последовательность инфиумов fₙ - неубывающая последовательность,
   значит, работает теорема Леви, и мы можем перейти к пределу под интегралом и
   получить что хотим.
   ▿
** LEARNED Теорема о произведении мер
   KW: ХАРАКТЕРИСТИЧЕСКИЕ ФУНКЦИИ
   Произведение мер есть мера на декартовом произведении пространств

   Пусть (X, ℵ, μ), (Y, ℶ, ν), μ, ν - меры, σ-конечные
   Тогда m(A × B) = μ(A)·ν(B) - σ-конечная мера в X × Y.

   ▵
   Докажем счетную аддитивность: рассмотрим счетные дизъюнктные объединения в X и Y.
   Рассмотрим характеристическую функцию для этого диз. объединения - это сумма харак. функций
   компонентов. Проинтегрируем эту сумму по мерам μ и ν, получим и слева, и справа то, что надо
   Сигма-конечность как-то очевидна
   ▿
** LEARNING Принцип Кавальери
   KW: ПО ИНДУКЦИИ ОТ ПРЯМОУГОЛЬНИКОВ КО ВСЕМУ, НЕПРЕРЫВНОСТЬ СВЕРХУ, МАЖОРИРОВАННАЯ СХОДИМОСТЬ, ЛЕБЕГОВО ПРОДОЛЖЕНИЕ
   Это о том, что можно находить объем, интегрируя высоту по площади или площадь по высоте.

   (X, ℵ, μ), (Y, ℶ, ν)
   m = ν × μ, μ, ν - σ-конечные, полные
   С ∈ ℵ × ℶ - некая фигура

   Тогда выполнено следующее:
   1. Cₓ - ν-измеримо при п.в. X
   2. x ↦ ν(Cₓ) - μ-измеримая* на X функция
   3. m(C) = ∫ₓ ν(Cₓ)dμ(x)

   ▵
   Делаем как бы по структурной индукции:
   сначала докажем для обобщенных прямоугольников (тут очевидно)
   потом для счетных объединений/пересечений, (объединения - как-то по определению, пересечения - по непрерывности сверху и мажорированной сходимости)
   потом для всех множеств меры 0, (берем надмножество меры 0 - объединение/пересечение из D, заюзаем полноту и ок)
   потом для всех конечномерных, (как объединение/пересечение + мн-во меры 0)
   и наконец для всех измеримых. (в силу сигма-конечности)
   ▿
** LEARNED Формула для Бета-функции
   KW: ТЕОРЕМА ТОНЕЛЛИ, ЗАМЕНА ПЕРЕМЕННЫХ
   Β(s, t) = ₀∫¹ xˢ⁻¹ · (1 - x)ᵗ⁻¹ dx = Γ(s)Γ(t)/Γ(s+t)

   ▵
   Рассмотрим Г(s)Г(t) - произведение интегралов. Занесем один под другой,
   объединим в двойной, сделаем 2 замены (y = u - x, x = uz) и все.
   ▿
** LEARNED Объем шара в ℝⁿ
   KW: ИНДУКЦИЯ, БЕТА-ФУНКЦИЯ, ЗАМЕНА ПЕРЕМЕННЫХ
   V(B(0, r)) = αₙ * r^n
   αₙ = (√π)ⁿ / Γ(n/2 + 1)

   ▵
   Рассмотрим единичный шар: из интеграла для его объема
   вычленим одно изменение и сведем получившееся к B-функции, домноженной
   на объем шара меньшей размерности. Раскроем по индукции и все посокращается.
   ▿
** LEARNED Теорема об вычислении интеграла по взвешенному образу меры
   KW: ПО ИНДУКЦИИ
   Чтобы проинтегрировать функцию по взвешенному образу меры, нужно проинтегрировать ее по
   оригинальной мере, домножив на вес.

   (X, A, μ), (Y, B, _)
   Φ : X → Y, ν = ∫wdμ,
   f - положительная, измеримая или суммируемая на Y, тогда
   ∫fdν = ∫_Φ⁻¹ f(Φ(x))w(x)dμ

   ▵
   Продвинемся так: характерисическая → ступенчатая → полож. измеримая → суммируемая
   1) очевидно
   2) очевидно из 1
   3) представим f как предел возрастающих ступ. функций + теорема Леви
   4) сделаем это для обеих срезок
   ▿
** LEARNED Критерий плотности
   KW: ТУДА И ОБРАТНО, СЖАТИЕ НЕРАВЕНСТВА
   Функция является плотностью меры ν отн. μ если ее инфиум и супремум не пускают ν далеко от μ

   (X, ℵ, μ), (Y, ℶ, _)
   X = Y, ℵ = ℶ,
   ν=∫_Φ⁻¹ wdμ, w - положительная, измеримая на X,

   w - плотность ν относительно μ тогда и только тогда, когда
   ∀ A ∈ ℵ : μA·inf w ≤ νA ≤ μA·supw

   ▵
   Необходимость очевидна, c достаточностью магия:
   разобьем множество A на кучу маленьких, где w ограничено между qᵏ и qᵏ⁻¹,
   поставим рядом неравенство из условия и неравенство для интеграла, пошафлим,
   устремим q к единице и все ок.
   ▿
** LEARNED Лемма об оценке мер образов кубов из окрестности точки дифференцируемости
   KW: ЛИНЕЙНЫЙ ОПЕРАТОР, РАСТЯНУЛИ ЧУТЬ-ЧУТЬ
   Образ такого куба дифференцируемым отображением имеет меру, отличающуюся от
   меры Лебега самого куба на определенную константу.

   Φ: O ⊂ ℝᵐ → ℝⁿ, a ∈ O, Φ дифф. в точке a.
   Пусть 0 < |det Φ'(a)| < C, λₘ - мера Лебега в ℝᵐ
   Тогда ∃Uₐ : ∀ Q - куб, Q ∈ Uₐ, a ∈ Q : λₙ(Φ(Q)) ≤ c · λₘQ

   ▵
   Распишем определение дифференцируемости для Ф, пошафлим и выделим лин. оператор
   Ψ (Ф'(a)⁻¹ со сдвигом). Он сдвигает точку x очень недалеко, ну значит, и Ф раздвинул
   точки ненамного дальше - а именно, на |det Ф'(a)|.
   ▿
** Лемма "Вариации на тему регулярности меры лебега"
** LEARNING Теорема о преобразовании меры Лебега при диффеоморфизме
   Мера диффеоморфного образа равна интегралу якобиана по прообразу.

   Φ: O ⊂ ℝⁿ → ℝⁿ - диффеоморфизм,
   ∀ b ∈ Mᵐ : λ(Φ(b)) = ∫_b |det Φ'(x)|dλ

   ▵
   Пиздец какой-то, мда. Доказываем для якобиана критерий плотности,
   Только правое неравенство - потому что это диффеоморфизм, и мы можем все то же самое
   говорить про его обратную функцию - тогда супремум поменяется с инфиумом.
   Доказываем его для кубов - от противного к противоречию с предыдущей леммой,
   отсюда следует верность для всех открытых множеств.
   Доказательство для не только открытых - это ебать, там че-то по регулярности
   меры выразили ее через инфиум открытых, подставили, и доказываем через какую-то
   поеботу что получилось ровно то, что нам нужно.
   ▿
** LEARNED Теорема о гладкой замене переменной в интеграле Лебега
   KW: ПРЯМОЕ СЛЕДСТВИЕ
   Когда заменяем переменные, надо подставить замену вместо вхождений и домножить на якобиан.

   Φ: O ⊂ ℝⁿ → ℝⁿ диффеоморфизм, O' = Φ(O), тогда
   f - положительная, измеримая на O' или суммируемая на O'
   ∫_O' fdλ = ∫_O f∘Φ(x)|det Φ'(x)|dλ

   ▵
   Прошлая теорема + теорема о взвешенном образе меры
   ▿
** LEARNED Формула Грина
   Как Стокс, только для двумерного случая

   D ⊂ ℝ² - компактное, односвязное, с C² - гладкой границей, (P, Q) - гл. векторное поле.
   Граница ∂D ориентирована согласованно стороне D. Тогда

   ∂D_∫Pdx + Qdy = D_∫∫(∂Q/∂x - ∂P/∂y)dxdy

   ▵
   Рассмотрим сначала "криволинейные прямоугольники" и поле (P, 0).
   Для такого легко посчитать как интеграл по площади, так и по контуру.
   Пошафлим их и убедимся, что они равны.
   Произвольное же множество можно разрезать на кучу различных крив. прямоугольников.
   ▿
** LEARNED Формула Стокса
   D - прост. глад. 2-мерная пов-ть в ℝ³,
   ∂D - С²-гладкая, (P, Q, R) - гл. векторное поле,
   ориентация границы согласована со стороной.
   Тогда:

   ∂D_∫Pdx + Qdy + Rdx = D_∫∫(R_y' - Q_z')dydz + (P_z' - Rₓ')dzdx + (Qₓ' - P_y')dxdy

   ▵
   Рассмотрим сначала только (P, 0, 0).
   Запараметризуем поверхность двумерными параметрами и сведем интеграл к двумерному.
   Там возпользуемся формулой Грина и скакнем обратно, когда увидим интеграл 2 рода.
   ▿
** LEARNED Формула Гаусса-Остроградского
   Интеграл по поверхности равен интегралу дивергенции по объему.

   D ⊂ ℝ³, ∂D - ориентированна полем внеш. нормалей.
   (P, Q, R) - гладкое поле в D. Тогда:

   ∂D_∫∫Pdx + Qdy + Rdz = D_∫∫∫(Pₓ' + Q_y' + R_z')dxdydz

   ▵
   Сначала рассмотрим "криволинейные параллелепипеды" и (0, 0, R).
   Отделим от тройного интеграла dz и возьмем его, убедимся, что получился
   в точности интеграл по поверхности.
   Произвольное мн-во можно разрезать на криволинейные прямоугольники
   ▿
** LEARNED Описание соленоидальных полей в терминах дивергенции
   Поле соленоидально, если его дивергенция всюду 0.

   V - гладкое век. поле. Эквивалентно:
   1) V - соленоидально (V = rot B)
   2) div V = 0

   ▵
   1 => 2: докажем, что div rot B = 0, просто расписав формулы.
   2 => 1: построим такое B. распишем формулу ротора, возьмем B₃ = 0, отталкиваясь
   от этого и от условия на дивергенцию, распишем B₁ и B₂ как интегралы от A-компонент
   ▿
** Предельный переход под знаком интеграла при наличии равномерной сходимости или L_{loc}
** LEARNED Правило Лейбница о дифференцируемости интеграла по параметру
   KW: ТИПА-ПРОИЗВОДНАЯ, МАЖОРИРОВАННАЯ СХОДИМОСТЬ
   Производная интеграла по параметру равна интегралу производной внутренней функции по этому параметру.

   (X, A, μ)
   f: X × Y → ℝ, Y ⊂ ℝ - промежуток

   1. x ↦ f(x, y) суммируемо
   2. f дифференцируемо по y при почти всех x
   3. f'_y удовлетворяет Lₗₒₖ в y0

   Тогда
   (∫f(x)dμ(x))'_y = ∫f'_y(x)dμ(x)

   ▵
   Рассмотрим типа-производную F(x, h) = (f(x, y₀ + h) - f(x, y₀))/h.
   Она стремится в нуле к частной производной, значит - непрерывна в 0.
   Докажем, что ее интеграл по x непрерывен в нуле (это то, что нужно, ведь ее интеграл - типа-производная I(y₀)
   Для этого надо показать Lₗₒₖ(0) для F, ну там из 3 условия легко следует.
   ▿
** Голоморфность интеграла типа Коши
** Теорема о предельном переходе в несобственном интеграле
** LEARNED Теорема о вложении пространств Lᵖ
   KW: НЕРАВЕНСТВО ГЕЛЬДЕРА
   В пространстве конечной меры L с большим p вложено в L с меньшим

   (X, ℵ, μ), μX < +∞, 1 ≤ s < r < +∞
   1) Lʳ ⊂ Lˢ
   2) |f|ₛ ≤ (μX)^(1/s - 1/r) · |f|ᵣ

   ▵
   1 пункт следует из 2, а 2 доказываем через неравенство Гельдера для f и 1.
   ▿
** Теорема о сходимости в Lᵖ и по мере
** LEARNED Полнота Lᵖ
   KW: ТЕОРЕМА ФАТУ
   Пространство Lᵖ полно.

   ▵
   Возьмем фундаментальную последовательность. Выделим из нее подпоследовательность
   такую, чтобы расстояние м/у соседями сжималось на каждом шаге вдвое. Тогда ряд из
   расстояний сходится (< 1). Возьмем и подставим иксы в этот ряд и докажем, что
   полученная функция почти везде конечна. Но если прибавить к ней еще первый член, то она
   телескопически сложится - так получим кандидата на предел. Аккуратно покажем,
   что этот кандидат конечен и действительно является пределом исходной последовательности
   ▿
** LEARNED Плотность в Lᵖ множества ступенчатых функций
   KW: ПРИБЛИЖЕНИЕ ФУНКЦИИ СТУПЕНЧАТЫМИ
   Множество ступенчатых функций плотно в Lᵖ (включая L∞)

   ▵
   Рассмотрим конечное p и ∞
   В обоих случаях приблизим нашу измеримую ограниченную функцию ступенчатыми,
   распишем норму в Lᵖ и покажем, что она сходится
   ▿

** LEARNED Лемма Урысона
   KW: ТОПОЛОГИЧЕСКАЯ НЕПРЕРЫВНОСТЬ
   Для пары непересек. замкнутых множеств существует непрерывная функция,
   которая на одном всегда 0, а на другом - 1.

   F₀, F₁ - замкнутые, непересекающиеся (в ℝᵐ)
   ∃ f - непрерывная, f|_F₀ = 0, f|_F₁ = 1

   ▵
   Понапихаем между этими множествами кучу открытых множеств в двоично-рациональными
   индексами. Возьмем функцию - инфиум от индекса множества, содержащего x, доопределим
   ее что она = 1 на F₁. Докажем что она непрерывна, для этого достаточно показать,
   что прообраз (-∞, s) открыт, а (-∞, t] - замкнут. Подумав, сопоставим этим
   прообразам объединение/пересечение каких-то дв. рациональных множество
   и увидим, что все получилось
   ▿
** LEARNED Плотность в Lᵖ непрерывных финитных функций
   KW: ПРИБЛИЖАТЬ К ФИНИТНЫМ, ЛЕММА УРЫСОНА
   Множество непрерывных финитных функций полно в Lᵖ

   ∀ p: 1 ≤ p < +∞ : C₀(ℝᵐ) - плотно в Lᵖ(ℝᵐ)

   ▵
   Возьмем ступенчатую функцию, которая лежит близко к нужной.
   Каждую ступеньку окружим плотненько с 2 сторон замкнутым и открытым множеством.
   Возьмем разделяющую функцию из леммы Урысона и вычтем ее из харак. функции ступеньки -
   получим что-то очень маленькое. Ну и соберем из таких (очевидно, финитных) функций
   линейную комбинацию, которая тоже будет близка к ступенчатой, а значит, и к целевой.
   ▿

** LEARNING Теорема о непрерывности сдвига
   KW: ФИНИТНЫЕ ФУНКЦИИ, РАВНОМЕРНАЯ НЕПРЕРЫВНОСТЬ
   Сдвиг функции непрерывен аж во всяких Lᵖ

   fₕ = f(x + h) - сдвиг - обладает следующими св-вами:
   1) f - равн. непрерывна на ℝᵐ ⇒ |fₕ - f|∞ → 0 (при h → 0)
   2) f ∈ Lᵖ(ℝᵐ), 1 ≤ p < +∞ ⇒ |fₕ - f|ₚ → 0
   3) f ∈ C[0, T] ⇒ |fₙ - f|∞ → 0
   4) f ∈ Lᵖ[0, T], 1 ≤ p < +∞ ⇒ |fₕ - f|ₚ → 0

   ▵
   1) легко из определения равн. непрерывности
   3) непрерывная на компакте функция равн. непрерывна на нем - значит, пункт 1
   4) возьмем непрерывную финитную функцию рядом, докажем непрерывность сдвига для нее:
      оценим интеграл сверху супремумом и сведем к пункту 1
   2) возьмем финитную функцию - можем сузить интеграл до компакта, где работает п. 4
   ▿
** LEARNED Лемма о вычислении коэффициентов тригонометрического ряда
   Коэффициенты Фурье функции можно вычислить как соответствующие интегралы от -π до π

   T(x) - тригонометрический ряд, Sₙ(x)  - его част. суммы.
   Пусть ∃ f ∈ L¹[-π, π], Sₙ → f в пр-ве L¹
   Тогда:
   1) aₖ = 1/π · ∫_{-π}^π f(x)cos(kx) dx
   2) bₖ = 1/π · ∫_{-π}^π f(x)sin(kx) dx
   3) Cₖ = 1/2π ·∫_{-π}^π f(x)eⁱᵏˣdx

   ▵
   Можно рассмотреть только aₖ - остальные аналогично.
   Домножим частичную сумму на coskx скалярно, раскроем по линейности, там везде останутся
   нули, кроме как раз aₖ. Перейдем к пределу в скалярном произведении, раскроем его по определению -
   получится нужный интеграл
   ▿
** LEARNED Теорема Римана-Лебега
   Интеграл функции на тригонометрический член по всему множеству стремится к нулю при росте k.

   E ⊂ ℝ - измеримо, f ∈ L¹(E). Тогда ₑ∫f(x)eⁱᵏˣ → 0, если k → +∞
   (ₑ∫f(x)cos(kx) → 0, ₑ∫f(x)sin(kx) → 0)

   ▵
   Будем считать, что f - нулевая за пределами E, значит, можем рассмотреть
   интеграл по всему ℝ. Подвинем аргумент на π/k, выйдет наружу минус.
   Возьмем среднее арифметическое от обычного интеграла и сдвига - это равно искомому
   интегралу - и по непрерывности сдвига это будет стремиться к нулю.
   ▿
** LEARNED Принцип локализации Римана
   Если функции равны в окрестности некой точки, то их частичные суммы Фурье в
   этой точке стремятся друг к другу.

   f, g ∈ L¹[-π, π], x₀ ∈ [-π, π], ∃ U(x₀) : ∀ x ∈ U(x₀) : f(x) = g(x).
   Тогда Sₙ(f, x₀) - Sₙ(g, x₀) → 0, n → ∞

   ▵
   Вместо двух функций рассмотрим из разность.
   Выразим частичные суммы через ядро Дирихле. Само ядро Дирихле выражается через поеботу
   с котангенсами, и это надо запомнить. Рассмотрим модуль частичных сумм.
   Пошафлим его, пооцениваем сверху, в итоге придем к тому, что получилось aₖ(h₁) + bₖ(h₂),
   а они по теореме Римана-Лебега стремятся к 0.
   Там надо доказать, что h₁ лежит в множестве, чтобы это работало. Там есть котангенс, он хуевый,
   но по условию функция нулевая в окрестности x₀, а вне нее этот котангенс ограничен - значит,
   можем оценить сверху
   ▿
** LEARNED Признак Дини. Следствия
   Если странный интеграл вокруг некоторой точки с какой-то константой конечен,
   то частичные суммы Фурье этой функции в этой точке стремятся к этой константе.

   f ∈ L¹[-π, π], x₀ ∈ [-π, π], S ∈ ℝ
   Пусть ₀∫ᵖⁱ (|f(x₀ + t) + f(x₀ - t) - 2S|/t)dt - конечен.
   Тогда Sₙ(f, x₀) → S

   Следствие 1:
   Если у функции существуют предел и производная слева и справа от точки,
   то частичные суммы в ней стремятся к среднему значению из двух пределов

   f ∈ L¹[-π, π], x₀ ∈ [-π, π], ∃ f(x₀ - 0), f(x₀ + 0),
   ∃ α± = lim{x → x₀ ± 0} (f(x) - f(x₀ ± 0))/(x - x₀)
   Тогда Sₙ(f, x₀) → 1/2 · (f(x₀ - 0) + f(x₀ + 0))

   Следствие 2:
   Если функция непрерывна в точке и имеет производные слева и справа от нее,
   то частичные суммы сходятся к значению функции в точке.

   f ∈ L¹[-π, π], x₀ ∈ [-π, π], f - непр. в x₀, ∃ α±
   Тогда Sₙ(f, x₀) → f(x₀)

   ▵
   Частичные суммы представляем через ядро Дирихле, как в прошлый раз,
   опять вылезет котангенс и aₖ с bₖ, но тут-то мы его домножим на t, и он станет непрерывным в нуле,
   а кроме него останется интеграл из условия, который конечен - ну значит, все норм оценивается

   Следствие 1: просто подставим в подынтегральное выражение данный S, получится сумма боковых производных,
   которая ограничена.
   Следствие 2: сразу из 1.
   ▿
** Корректность определения свертки
** LEARNED Свойства свертки функции из Lᵖ с функцией из L^q
   Свертка функций из "сопряженных по параметру" пространств непрерывна
   и не превышает по норме произведения норм функций.

   f ∈ Lᵖ[-π, π], K ∈ L^q[-π, π], 1/p + 1/q = 1, 1 ≤ p < +∞
   Тогда f ⋆ K - непрерывна на [-π, π],
   и |f ⋆ K|₁ ≤ |f|ₚ · |K|_q
   Эта свертка непрерывна и ее норма не превышает произведения норм функций

   f ∈ Lᵖ[-π, π], K ∈ L^q[-π, π], 1 ≤ p < +∞
   Тогда (f ⋆ K) ∈ L¹[-π, π] - непрерывна, и |f ⋆ K|₁ ≤ |f|ₚ · |K|_q

   ▵
   2 утверждение - это ровно неравенство Гельдера, по сути.
   Докажем непрерывность. Возьмем маленький сдвиг, докажем, что разница между ним
   и самой сверткой стремится к нулю. Пошафлим, пооцениваем, посередине опять
   возникнет неравенство Гельдера, пошафлим дальше, придем к сдвигу, который непрерывен.
   ▿
** LEARNING Теорема о свойствах аппроксимативной единицы
   Аппроксимативная единица - нейтральный элемент относительно свертки

   Kₕ - a. е, h₀ - ее предельная точка. Тогда:
   1) f ∈ C[-π, π] ⇒ f ⋆ Kₕ ⇉ f при h → h₀
   2) f ∈ Lᵖ[-π, π] ⇒ |f ⋆ Kₕ - f|ₚ → 0
   3) f ∈ L¹, f - непр. в x₀, Kₕ - усиленная а. е.
      Тогда f ⋆ Kₕ - непрерывна в x₀, (f ⋆ Kₕ)(x₀) → f(x₀) при h → h₀

   ▵
   1) Возьмем δ из равн. непрерывности, с ее помощью и через ограниченность а. е.
      оценим кусок интеграла на (-δ, δ), потом оценим на всем что осталось - тут сыграет 3 св-во а.е.
   3) Кусок для дельты - как в прошлом пункте, на остатке оцениваем с помощью esssup
   2) Рассмотрим норму в L¹ - она сильнее. Распишем и ее и свертку по определению, поменяем местами
      интегралы, ПОЧЕМУ-ТО скажем, что если разделить а.е. на ее норму, она станет усиленной, скажем,
      что внутренний интеграл - это непрерывная в нуле функция и сведем к 3 пункту
   ▿
** LEARNED Теорема Коши о перманентности метода средних арифметических
   Cуммa ряда средними арифметическими равна обычной сумме ряда (если та существует)

   ∑aₙ = S ⇒ ∑aₙ (ср. ариф.) = S

   ▵
   Просто аккуратно оценим эпсилоном из определения предела для
   обычных частичных сумм средние арифметические.
   ▿
** LEARNED Теорема Фейера
   Теорема о том, что ряд Фурье можно складывать и по методу средних
   арифметических тоже, и все будет работать.

   σₙ = (1/(n + 1))∑ₖⁿSₖ(f) - сумма Фейера
   Sₙ(f, x) = ₋ₚᵢ∫ᵖⁱf(x + t)Dₙ(t)dt
   σₙ(f, x) = ₋ₚᵢ∫ᵖⁱf(x + t)Фₙ(t)dt

   1) f ∈ C[-π, π] ⇒ σₙ(f, x) ⇉ f(x)
   2) f ∈ Lᵖ[-π, π] ⇒ |σₙ(f, x) - f(x)|ₚ → 0
   3) f ∈ L¹, f - непрерывно в x ⇒ σₙ(f, x) → f(x)

   ▵
   Если бы ядро Фейера было усиленной а. е., все бы работало -
   докажем, что так и есть. 1ое свойство - легко проверяется руками,
   2 свойство следует из первого и положительности ядра, третье свойство
   оценивается формула с синусами сверху, и видим, что она стремится к нулю.
   ▿